name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  release:
    uses: calebjakemossey/ci-workflows/.github/workflows/release.yaml@v1
    with:
      image-name: assignment-example-ros-pkg
      ros-distro: humble
    secrets:
      registry-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
